//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
/// </summary>
// StronglyTypedResourceBuilder generó automáticamente esta clase
// a través de una herramienta como ResGen o Visual Studio.
// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
// con la opción /str o recompile su proyecto de VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Eagle_Spy_Applications {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Eagle_Spy_Applications() {
    }
    
    /// <summary>
    ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eagle_Spy.Applications", typeof(Eagle_Spy_Applications).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _as {
        get {
            object obj = ResourceManager.GetObject("as", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap account {
        get {
            object obj = ResourceManager.GetObject("account", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap add {
        get {
            object obj = ResourceManager.GetObject("add", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Android_logo_2019__stacked_ {
        get {
            object obj = ResourceManager.GetObject("Android_logo_2019_(stacked)", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Android_logo_2019__stacked_1 {
        get {
            object obj = ResourceManager.GetObject("Android_logo_2019_(stacked)1", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap applications {
        get {
            object obj = ResourceManager.GetObject("applications", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap calls {
        get {
            object obj = ResourceManager.GetObject("calls", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap contacts {
        get {
            object obj = ResourceManager.GetObject("contacts", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap download_removebg_preview {
        get {
            object obj = ResourceManager.GetObject("download-removebg-preview", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap download_removebg_preview1 {
        get {
            object obj = ResourceManager.GetObject("download-removebg-preview1", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap eagle {
        get {
            object obj = ResourceManager.GetObject("eagle", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap folder {
        get {
            object obj = ResourceManager.GetObject("folder", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_access_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-access-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_android_studio_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-android-studio-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_back_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-back-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_bank_1001 {
        get {
            object obj = ResourceManager.GetObject("icons8-bank-1001", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_block_user_96 {
        get {
            object obj = ResourceManager.GetObject("icons8-block-user-96", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_browser_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-browser-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_cell_phone_with_up_and_down_arrows_96 {
        get {
            object obj = ResourceManager.GetObject("icons8-cell-phone-with-up-and-down-arrows-96", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_clean_50 {
        get {
            object obj = ResourceManager.GetObject("icons8-clean-50", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_client_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-client-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_client_1001 {
        get {
            object obj = ResourceManager.GetObject("icons8-client-1001", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_cloud_64__1_1 {
        get {
            object obj = ResourceManager.GetObject("icons8-cloud-64 (1)1", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_cloud_641 {
        get {
            object obj = ResourceManager.GetObject("icons8-cloud-641", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_contact_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-contact-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_cut_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-cut-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_delete_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-delete-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_electric_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-electric-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_email_48 {
        get {
            object obj = ResourceManager.GetObject("icons8-email-48", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_folder_32 {
        get {
            object obj = ResourceManager.GetObject("icons8-folder-32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_folder_50 {
        get {
            object obj = ResourceManager.GetObject("icons8-folder-50", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_folder_501 {
        get {
            object obj = ResourceManager.GetObject("icons8-folder-501", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_google_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-google-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_google_play_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-google-play-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_guarantee_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-guarantee-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_hand_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-hand-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_internet_antenna_30 {
        get {
            object obj = ResourceManager.GetObject("icons8-internet-antenna-30", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_keyboard_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-keyboard-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_kindle_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-kindle-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_location_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-location-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_lock_643 {
        get {
            object obj = ResourceManager.GetObject("icons8-lock-643", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_lock_96 {
        get {
            object obj = ResourceManager.GetObject("icons8-lock-96", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_lock_961 {
        get {
            object obj = ResourceManager.GetObject("icons8-lock-961", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_locked_network_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-locked-network-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_message_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-message-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_microsoft_admin_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-microsoft-admin-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_minus_50 {
        get {
            object obj = ResourceManager.GetObject("icons8-minus-50", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_mobile_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-mobile-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_no_audio_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-no-audio-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_notification_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-notification-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_number_pad_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-number-pad-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_ocr_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-ocr-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_online_support_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-online-support-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_padlock_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-padlock-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_padlock_641 {
        get {
            object obj = ResourceManager.GetObject("icons8-padlock-641", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_phone_1001 {
        get {
            object obj = ResourceManager.GetObject("icons8-phone-1001", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_play_record_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-play-record-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_play_record_641 {
        get {
            object obj = ResourceManager.GetObject("icons8-play-record-641", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_power_off_button_641 {
        get {
            object obj = ResourceManager.GetObject("icons8-power-off-button-641", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_public_speaking_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-public-speaking-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_restart_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-restart-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_restart_641 {
        get {
            object obj = ResourceManager.GetObject("icons8-restart-641", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_send_30 {
        get {
            object obj = ResourceManager.GetObject("icons8-send-30", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_shortcut_1001 {
        get {
            object obj = ResourceManager.GetObject("icons8-shortcut-1001", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_sms_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-sms-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_speaker_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-speaker-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_stop_100 {
        get {
            object obj = ResourceManager.GetObject("icons8-stop-100", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_stop_503 {
        get {
            object obj = ResourceManager.GetObject("icons8-stop-503", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_target_audience_68 {
        get {
            object obj = ResourceManager.GetObject("icons8-target-audience-68", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_terminal_641 {
        get {
            object obj = ResourceManager.GetObject("icons8-terminal-641", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_video_64 {
        get {
            object obj = ResourceManager.GetObject("icons8-video-64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_x_30 {
        get {
            object obj = ResourceManager.GetObject("icons8-x-30", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_x_642 {
        get {
            object obj = ResourceManager.GetObject("icons8-x-642", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_xbox_menu_30 {
        get {
            object obj = ResourceManager.GetObject("icons8-xbox-menu-30", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap IonLocked {
        get {
            object obj = ResourceManager.GetObject("IonLocked", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap LetsIconsReturn {
        get {
            object obj = ResourceManager.GetObject("LetsIconsReturn", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MaterialSymbolsCircle {
        get {
            object obj = ResourceManager.GetObject("MaterialSymbolsCircle", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MaterialSymbolsCloseRounded {
        get {
            object obj = ResourceManager.GetObject("MaterialSymbolsCloseRounded", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MaterialSymbolsMinimizeRounded {
        get {
            object obj = ResourceManager.GetObject("MaterialSymbolsMinimizeRounded", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap OpenToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("OpenToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Panel6_BackgroundImage {
        get {
            object obj = ResourceManager.GetObject("Panel6.BackgroundImage", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap pegaso {
        get {
            object obj = ResourceManager.GetObject("pegaso", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap pegasus {
        get {
            object obj = ResourceManager.GetObject("pegasus", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap photo_2023_11_21_13_40_14 {
        get {
            object obj = ResourceManager.GetObject("photo_2023-11-21_13-40-14", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap QQ20241001_173026 {
        get {
            object obj = ResourceManager.GetObject("QQ20241001-173026", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap QQ20241001_173033 {
        get {
            object obj = ResourceManager.GetObject("QQ20241001-173033", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap QQ20241001_174754 {
        get {
            object obj = ResourceManager.GetObject("QQ20241001-174754", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap remo {
        get {
            object obj = ResourceManager.GetObject("remo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_1 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_1", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_11 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_11", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_2 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_2", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_21 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_21", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_3 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_3", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_4 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_4", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_5 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_5", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_6 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_6", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_7 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_7", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_8 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_8", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap sms {
        get {
            object obj = ResourceManager.GetObject("sms", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TeenyiconsUnlockSolid {
        get {
            object obj = ResourceManager.GetObject("TeenyiconsUnlockSolid", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap VaadinPaperplane {
        get {
            object obj = ResourceManager.GetObject("VaadinPaperplane", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
